######################################################################
##
## Filename: WAV_TB.udo
## Created on: Fri Apr 18 18:55:40 Västeuropa, sommartid 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
