######################################################################
##
## Filename: WAV_TB.udo
## Created on: Sat Mar 22 14:03:11 Västeuropa, normaltid 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
